version: '3.8'

services:
  database:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fullUser
      POSTGRES_PASSWORD: hasloDoProjektuFullstack
      POSTGRES_DB: meal_planner_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
